"""empty message

Revision ID: 09002a957dbc
Revises: 22adaa7da67e
Create Date: 2023-05-24 08:44:33.501409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09002a957dbc'
down_revision = '22adaa7da67e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_filtered_books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_skipped', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_filtered_books', schema=None) as batch_op:
        batch_op.drop_column('user_skipped')

    # ### end Alembic commands ###
