"""empty message

Revision ID: 22adaa7da67e
Revises: dd2a62be8c47
Create Date: 2023-05-22 15:16:16.340284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22adaa7da67e'
down_revision = 'dd2a62be8c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_filtered_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('user_vote', sa.Boolean(), nullable=True),
    sa.Column('user_favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_filtered_genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('user_vote', sa.Boolean(), nullable=True),
    sa.Column('user_favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_filtered_narrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('narrator_id', sa.Integer(), nullable=True),
    sa.Column('user_vote', sa.Boolean(), nullable=True),
    sa.Column('user_favorite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['narrator_id'], ['narrators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_favorite_genres')
    op.drop_table('user_favorite_narrators')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_favorite_narrators',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('narrator_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['narrator_id'], ['narrators.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorite_genres',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('genre_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_filtered_narrators')
    op.drop_table('user_filtered_genres')
    op.drop_table('user_filtered_authors')
    # ### end Alembic commands ###
